import type { Metadata } from 'next'
import './globals.css'
import '@xyflow/react/dist/style.css'
import Providers from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <main className='min-h-screen w-screen'>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
